<a href="https://colab.research.google.com/github/kskrao219/jovian.ai/blob/main/linear_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [121]:
# Jovian Commit Essentials
# Please retain and execute this cell without modifying the contents for `jovian.commit` to work
!pip install jovian --upgrade -q
import jovian
jovian.utils.colab.set_colab_file_id('1bK11013cI0guvKjIW5uzkhJkmDic-nUX')

In [122]:
!pip install jovian --upgrade --quiet

In [123]:
 import numpy as np
 import torch as tr
 import pandas as pd

In [124]:
#input(temp,rainfall,humidity)
inputs = np.array([[73,67,43],
                   [91,88,64],
                   [87,134,58],
                   [102,43,37],
                   [69,96,70]],dtype='float32')

In [125]:
#targets/outputs (apples , oranges)
targets = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119]], dtype='float32')

In [126]:
#convert numpy arrays to torch tensors
inputs=tr.from_numpy(inputs)
targets=tr.from_numpy(targets)
print(inputs)
print(targets)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [127]:
#weights and biases
w=tr.randn(2,3,requires_grad=True)#creates random matrix
b=tr.randn(2,requires_grad=True)
print(w)
print(b)

tensor([[ 0.1314, -0.8679,  0.1804],
        [ 0.6853, -1.0474,  0.7034]], requires_grad=True)
tensor([0.8134, 1.5068], requires_grad=True)


In [128]:
w

tensor([[ 0.1314, -0.8679,  0.1804],
        [ 0.6853, -1.0474,  0.7034]], requires_grad=True)

In [129]:
def model(x): 
  return x @ w.t() + b # @ is used for matrix multiplication in pytorch and python , w.t() is used for transposing

In [130]:
w.t()

tensor([[ 0.1314,  0.6853],
        [-0.8679, -1.0474],
        [ 0.1804,  0.7034]], grad_fn=<TBackward>)

In [131]:
preds = model(inputs)
print(preds)

tensor([[-39.9881,  11.6062],
        [-52.0614,  16.7181],
        [-93.5936, -38.4244],
        [-16.4286,  52.3981],
        [-60.8140,  -2.5180]], grad_fn=<AddBackward0>)


In [132]:
#compare with targets
print(targets)

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [133]:
#loss functions


In [134]:
#MSE loss function
def mse(t1,t2):
  diff = t1-t2
  return tr.sum(diff*diff)/diff.numel() #numel is used for getiing no of elements

In [135]:
#compute loss
loss = mse(preds,targets)
print(loss) 

tensor(15533.0156, grad_fn=<DivBackward0>)


In [136]:
loss.backward()

In [137]:
print(w)
print(w.grad)

tensor([[ 0.1314, -0.8679,  0.1804],
        [ 0.6853, -1.0474,  0.7034]], requires_grad=True)
tensor([[-10566.8486, -12801.3447,  -7572.5371],
        [ -6732.0908,  -9060.7324,  -5156.8232]])


In [138]:
#optimise gradients

In [139]:
#new calculations clear previous grads

In [140]:
w.grad.zero_()
b.grad.zero_()
print(w.grad)
print(b.grad)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([0., 0.])


In [141]:
#ADJUST WEIGHTS AND BIASES USING GRADIENT DESCENT
#1 GENERATE PREDICTIONS
#2 CALCULATE LOSSES 
#3 COMPUTE GRADIENTS WRT THE WEIGHTS AND BIASES 
#4 ADJUST THE WEIGHTS BY SUBTRACTING A SMALL QUANTITY PROPORTIONAL TO THE GRADIENT
#5 RESET THE GRADIENTS TO ZERO

In [142]:
#generate predictions
preds=model(inputs)
print(preds)

tensor([[-39.9881,  11.6062],
        [-52.0614,  16.7181],
        [-93.5936, -38.4244],
        [-16.4286,  52.3981],
        [-60.8140,  -2.5180]], grad_fn=<AddBackward0>)


In [143]:
#calculate the loss
loss=mse(preds,targets)
print(loss)

tensor(15533.0156, grad_fn=<DivBackward0>)


In [144]:
#compute gradients
loss.backward()
print(w.grad)
print(b.grad)

tensor([[-10566.8486, -12801.3447,  -7572.5371],
        [ -6732.0908,  -9060.7324,  -5156.8232]])
tensor([-128.7771,  -84.0440])


In [145]:
#adjust weights and reset gradients
with tr.no_grad():
  w-=w.grad * (10**-5)
  b-=b.grad * (10**-5)
  w.grad.zero_()
  b.grad.zero_()
 

In [146]:
print(w)
print(b)

tensor([[ 0.2371, -0.7399,  0.2561],
        [ 0.7527, -0.9568,  0.7550]], requires_grad=True)
tensor([0.8147, 1.5076], requires_grad=True)


In [147]:
#calculate losss
preds = model(inputs)
loss=mse(preds,targets)
print(loss)

tensor(11097.7344, grad_fn=<DivBackward0>)


In [148]:
#train for 100 epochs
for i in range(100):
  preds  = model(inputs)
  loss = mse(preds,targets)
  loss.backward()
  with tr.no_grad():
    w-=w.grad * (10**-5)
    b-=b.grad * (10**-5)
    w.grad.zero_()
    b.grad.zero_()

 

In [149]:
preds=model(inputs)
loss=mse(preds,targets)
print(loss)


tensor(559.2199, grad_fn=<DivBackward0>)


In [150]:

targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])

In [151]:
preds #predictions

tensor([[ 63.7608,  78.5408],
        [ 87.3968, 108.4642],
        [ 96.2886, 102.0034],
        [ 58.6962,  83.6190],
        [ 89.1597, 105.7978]], grad_fn=<AddBackward0>)

In [152]:
#train for 100 epochs
for i in range(100):
  preds  = model(inputs)
  loss = mse(preds,targets)
  loss.backward()
  with tr.no_grad():
    w-=w.grad * (10**-5)
    b-=b.grad * (10**-5)
    w.grad.zero_()
    b.grad.zero_()

In [153]:
preds=model(inputs)
loss=mse(preds,targets)
print(loss)

tensor(158.8285, grad_fn=<DivBackward0>)


In [154]:
preds

tensor([[ 60.7113,  74.7137],
        [ 85.0142, 105.3466],
        [106.6100, 115.2463],
        [ 40.9417,  61.3248],
        [ 95.3752, 113.3838]], grad_fn=<AddBackward0>)

In [155]:
!pip install jovian --upgrade -q

In [156]:
import jovian

In [157]:
jovian.commit(project='02_linear_regression-live')

[jovian] Detected Colab notebook...
[jovian] Please enter your API key ( from https://jovian.ai/ ):
API KEY: ··········
[jovian] Uploading colab notebook to Jovian...
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/kskrao2192000/02-linear-regression-live


'https://jovian.ai/kskrao2192000/02-linear-regression-live'