<a href="https://colab.research.google.com/github/kskrao219/jovian.ai/blob/main/pyTorch_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install torch numpy --quiet

In [ ]:
import torch

In [ ]:
t1=torch.tensor(4.0) #floating point is taken to avoid loss 
print(t1)

tensor(4.)


In [ ]:
t1.dtype

torch.float32

In [ ]:
#vector- 1 dimesional
t2=torch.tensor([1.,2,3,4,6])
t2


tensor([1., 2., 3., 4., 6.])

In [ ]:

#matrix-2 dimensional
t3=torch.tensor([[1,2,3],
                [2,4,7],
                [1,3,5]])
t3

tensor([[1, 2, 3],
        [2, 4, 7],
        [1, 3, 5]])

In [ ]:

#3-d array
t4=torch.tensor([[[1,2,3],
                 [14,4,1]],
                [[2,3,4],
                 [4,5,7]]])
t4


tensor([[[ 1,  2,  3],
         [14,  4,  1]],

        [[ 2,  3,  4],
         [ 4,  5,  7]]])

In [ ]:
t1=torch.tensor(4.0)

In [ ]:
t1

tensor(4.)

In [ ]:
t1.shape

torch.Size([])

In [ ]:
print(t2)
t2.shape

tensor([1., 2., 3., 4., 6.])


torch.Size([5])

In [ ]:
print(t4)
t4.shape

tensor([[[ 1,  2,  3],
         [14,  4,  1]],

        [[ 2,  3,  4],
         [ 4,  5,  7]]])


torch.Size([2, 2, 3])

In [ ]:
#t5=torch.tensor([[[4,2.,1], #improper shape
 #                [2,6],
 #                [2,5,1]])

In [ ]:
#TENSORS OPERATIONS AND GRADIENTS

In [ ]:
x=torch.tensor(3.0)
y=torch.tensor(4.0,requires_grad=True)
z=torch.tensor(5.,requires_grad=True)
print(x,y,z)


tensor(3.) tensor(4., requires_grad=True) tensor(5., requires_grad=True)


In [ ]:
#AIRTHMETIC OPERATIONS

In [ ]:
a=x * y + z
a

tensor(17., grad_fn=<AddBackward0>)

In [ ]:
#COMPUTE DERIVATIVES
a.backward()

In [ ]:
#DISPLAY GRADIENTS
print('da/dx',x.grad)
print('da/dy',y.grad)
print('da/dz',z.grad)

da/dx None
da/dy tensor(3.)
da/dz tensor(1.)


In [ ]:
#INTEROPERABILITY WITH UMPY


In [ ]:
import numpy as np
x=np.array([[1,2],
            [2,4]])
x


array([[1, 2],
       [2, 4]])

In [ ]:
#CONVERY NUMPY ARRAY INTO A TORCH TENSOR
q=torch.from_numpy(x)
q

tensor([[1, 2],
        [2, 4]])

In [ ]:
x.dtype,q.dtype

(dtype('int64'), torch.int64)

In [ ]:
#CONVERY TENSOR  INTO A NUMPY 
v=q.numpy()
v


array([[1, 2],
       [2, 4]])

In [ ]:
!pip install jovian --upgrade --quiet

     |████████████████████████████████| 71kB 3.3MB/s 


In [ ]:
import jovian

In [ ]:
jovian.commit(project='01-pytorch-basics-live')

[jovian] Detected Colab notebook...


[jovian] Error: Colab File Id is not provided. Make sure to execute the cell where the Id is set.
